#!/usr/bin/env bash
#5-4_bad_luck_8_is_your_chance


count=0

while [ $count -lt 10 ];
do
if [ $count -eq 4]
then
echo "bad luck"
elif [ $count -eq 8]
then
echo "good luck"
else
echo "Best School"
fi
let count=count+1
done
